sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial main"
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe"
    - sudo apt-get update
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
    - mkdir -p ~/texmf/tex/latex/
    - git clone https://github.com/xdanaux/moderncv.git ~/texmf/tex/latex/moderncv/
    - mktexlsr

script:
    - pdflatex -halt-on-error *.tex

env:
    global:
        - GIT_NAME="Denton Liu"
        - GIT_EMAIL="liu.denton@gmail.com"
        - GIT_URL="git@github.com:Denton-L/resume.git"
        - ENCRYPTION_LABEL="3b28f2cf6bf8"
        - KEY_LOCATION=".travis/deploy_key"

deploy:
    provider: script
    script: .travis/deploy.bash
    skip_cleanup: true
    on:
        branch: master
