before_install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - mkdir -p ~/texmf/tex/latex/
    - wget https://launchpad.net/moderncv/trunk/1.5.1/+download/moderncv-1.5.1.zip
    - unzip moderncv-1.5.1.zip
    - mv moderncv/ ~/texmf/tex/latex/
    - mktexlsr

script:
    - pdflatex -halt-on-error *.tex

env:
    global:
        - GIT_NAME="Denton Liu"
        - GIT_EMAIL="liu.denton+github@gmail.com"
        - GIT_URL="git@github.com:Denton-L/resume.git"
        - ENCRYPTION_LABEL="3b28f2cf6bf8"
        - KEY_LOCATION=".travis/deploy_key"

deploy:
    provider: script
    script: .travis/deploy.bash
    skip_cleanup: true
    on:
        branch: master
