name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: DentonLiuResume.tex
          pre_compile: 'tlmgr update --self && tlmgr install moderncv'
      - uses: actions/upload-artifact@v2
        with:
          name: DentonLiuResume
          path: DentonLiuResume.pdf
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: DentonLiuResume
          path: gh-pages
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: gh-pages
          GIT_CONFIG_NAME: Denton Liu
          GIT_CONFIG_EMAIL: liu.denton@gmail.com
          COMMIT_MESSAGE: 'Automatic build by GitHub Actions: ${{ github.sha }}'
          SINGLE_COMMIT: true
